apiVersion: v1
kind: Pod
metadata:
  name: hook-dome1
spec:
  containers:
  - name: hook-demo1
    image: nginx
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh","-c","echo Hello > /usr/share/message"]
