apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik
  annotations:
    kubernetes.io/ingress.class: traefik-v2.8
#    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
    - host: traefik.dev.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: traefik
              port:
                number: 8080

