apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-nginx
  annotations:
    kubernetes.io/ingress.class: traefik
#    kubernetes.io/ingress.class: traefik-v2.8
#    ingress.kubernetes.io/rewrite-target: /
#    traefik.ingress.kubernetes.io/router.entrypoints: websecure

spec:
  rules:
    - host: traefik.test.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: traefik
              port:
                number: 8080

