apiVersion: v1
kind: Service
metadata:
  name: dtm-svc
  labels:
    app: dtm
spec:
  ports:
    - port: 36790
      targetPort: 36790
      name: grpc
      appProtocol: grpc
    - port: 36789
      targetPort: 36789
      name: http
      appProtocol: http
  selector:
    app: dtm
  type: NodePort
